name: host jobs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: tar files
              run: |
                mkdir ../build 
                cp -TR . ../build
                tar -cvf deploy.tar ../build/
                
            - name: deploy website to host
              uses: appleboy/scp-action@master
              env:
                  HOST: ${{ secrets.HOST }}
                  USERNAME: ${{ secrets.USERNAME }}
                  PORT: ${{ secrets.PORT }}
                  KEY: ${{ secrets.KEY }}
              with:
                  source: "*"
                  target: "/var/www/"
                  strip_components: 1
